# Generated by nixos-generate-config — replace this with the real file from your work laptop.
# On the laptop, run: sudo nixos-generate-config --show-hardware-config
# Then paste the output here.
_: { }
