# Generated by nixos-generate-config — replace this with the real file from your laptop.
# On the laptop, run: sudo nixos-generate-config --show-hardware-config
# Then paste the output here.
{ ... }: { }
