{ pkgs, ... }:

{
  packages = [
    pkgs.nixfmt
    pkgs.statix
    pkgs.deadnix
    pkgs.nixd
    pkgs.fd
  ];

  # https://devenv.sh/git-hooks/ — runs on every commit.
  # hardware-configuration.nix files are generated by nixos-generate-config
  # and explicitly marked "do not modify" — excluded so a future hardware
  # refresh can be committed without fighting the linters over someone
  # else's generated code style.
  git-hooks.hooks = {
    nixfmt-rfc-style.enable = true;
    statix = {
      enable = true;
      excludes = [ "hosts/.*/hardware-configuration\\.nix$" ];
    };
    deadnix = {
      enable = true;
      excludes = [ "hosts/.*/hardware-configuration\\.nix$" ];
    };
  };

  scripts.fmt.exec = ''
    fd -e nix -x nixfmt
  '';

  scripts.lint.exec = ''
    statix check .
    deadnix . --exclude hosts/*/hardware-configuration.nix
  '';

  enterShell = ''
    echo "nix-dots devshell: run 'fmt' to format, 'lint' to check for issues."
  '';
}
