# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# DO NOT hand-edit this file. It is machine-generated by NixOS.
#
# HOW TO GET YOUR REAL hardware-configuration.nix:
#
#   On your NixOS VM, run:
#       sudo nixos-generate-config --show-hardware-config
#
#   Then copy the output here, replacing this entire file.
#   Or run:
#       sudo nixos-generate-config --dir /tmp/hw
#   and copy /tmp/hw/hardware-configuration.nix
#
# This placeholder exists so the flake can be committed to git before
# being deployed. The real file is machine-specific and usually NOT
# committed (add it to .gitignore if you use multiple machines).
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
{ ... }:
{
  # Replace this file with the output of: sudo nixos-generate-config --show-hardware-config
}
